# Generated by Django 4.2 on 2023-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
